### ISSUE TITLE
BUG - Chapter 3 - colorWheels()

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [PacktPublishing/D3.js-4.x-Data-Visualization#3]
BUG - Chapter 3 - colorWheels()

In the creation of the path elements,
anonymous function calls (d,i,j) => {...} use a 3rd parameter j,
where j isn't any scalar index (as in d3.v3),
but now (in d3.v4) j is a [] of path DOM nodes.

see e.g.:
- http://stackoverflow.com/questions/38233003/d3-js-v4-how-to-access-parent-groups-datum-index/38235820#38235820
  and
- https://github.com/d3/d3-selection/issues/47

Therefore the call's to func. angle(j) will now fail ...

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
